### ISSUE TITLE
pecha.org alignment serializer (4 days)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#15]
## Description
Currently we have a vision and planning to store all our data in STAM format. And one of the entity that heavily works on tibetan texts, its translation and commentaries is pecha.org. So to directly and simply give data to pecha.org , there is a dire need of serializer from STAM toolkit to pecha.org

## Pecha.org Documentation
[json format](https://github.com/OpenPecha/pecha.org-data/blob/main/docs/jsonFormat.md
)
[read me](https://github.com/OpenPecha/pecha.org-data/blob/main/README.md
)

## Expected Output
A json file in simple text format (refer to docs above) of an Chojuk alignment from [here](https://github.com/OpenPecha/toolkit-v2/issues/6#issuecomment-2255884384)

## Implementation Steps

- [x] read alignment annotations 
- [x] read alignment and pecha metadata
- [x] generate json format based on pecha.org documentation
- [x] double check with pecha.org tech team(sandup)

Modification  [needed](https://github.com/OpenPecha/toolkit-v2/issues/15#issuecomment-2264877843)

- [x] add author metadata
- [x] place <**br**> in proper place in segment
- [x] fix books feature should be in list rather than dict

**Comment by tenzin3** [comment]
@lobsam 

Below is the output JSON for the pecha.org . Note that the values for the titles are dummy values. Please check if the format meets your standards.

```
{
  "target": {
    "books": {
      "title": " Source Title 1",
      "language": "bo",
      "version_source": "www.github.com/PechaData/IDBEEDAAE/base/389e.txt",
      "direction": "ltr",
      "content": [
        [
          "སངས་རྒྱས་དང་བྱང་ཆུབ་སེམས་དཔའ་ཐམས་ཅད་ལ་ཕྱག་འཚལ་ལོ།། བདེ་གཤེགས་ཆོས་ཀྱི་སྐུ་མངའ་སྲས་བཅས་དང་།། ཕྱག་འོས་ཀུན་ལའང་གུས་པར་ཕྱག་འཚལ་ཏེ།།\n",
          "བདེ་གཤེགས་སྲས་ཀྱི་སྡོམ་ལ་འཇུག་པ་ནི།། ལུང་བཞིན་མདོར་བསྡུས་ནས་ནི་བརྗོད་པར་བྱ།།\n",
          "སྔོན་ཆད་མ་བྱུང་བ་ཡང་འདིར་བརྗོད་མེད།། སྡེབ་སྦྱོར་མཁས་པའང་བདག་ལ་ཡོད་མིན་ཏེ།། དེ་ཕྱིར་གཞན་དོན་བསམ་པའང་བདག་ལ་མེད།། རང་གི་ཡིད་ལ་བསྒོམ་ཕྱིར་ངས་འདི་བརྩམས།།\n",
          "དགེ་བ་བསྒོམ་ཕྱིར་བདག་གི་དད་པའི་ཤུགས།། འདི་དག་གིས་ཀྱང་རེ་ཞིག་འཕེལ་འགྱུར་ལ།།\n",
          "བདག་དང་སྐལ་བ་མཉམ་པ་གཞན་གྱིས་ཀྱང་།། ཅི་སྟེ་འདི་དག་མཐོང་ན་དོན་ཡོད་འགྱུར།།"
        ]
      ]
    }
  },
  "source": {
    "books": {
      "title": " Target Title 1",
      "language": "en",
      "version_source": "www.github.com/PechaData/IA4C08511/base/0d78.txt",
      "direction": "ltr",
      "content": [
        [
          "A Guide To The Bodhisattava's Way of Life Homage to all Buddha's and Bodhisattvas Respectfully I prostrate myself to the Sugatas Who are endowed with the Dharmakaya, As well as to their Noble Children And to all who are worthy of veneration.\n",
          "Here I shall explain how to engage in the vows of the Buddha's Children, The meaning of which I have condensed in accordance with the scriptures.\n",
          "Thete is nothing hete that has not been explained before And I have no skill in the art of thetotic; Therefore, lacking any intention to benefit others, I write this in order to acquaint it to my mind.\n",
          "For due to acquaintance with what is wholesome, The force of my faith may for a short while increase because of these.\n",
          "If, however, these are seen by others Equal in fortune to myself, it may be meaningful."
        ]
      ]
    }
  }
}
```

**Comment by tenzin3** [comment]
@lobsam , One question i have is for metadata such as ```Author```, if there are more than one author, then how should be presented in the json.

**Option 1**
```
"author": ["Author 1", "Author 2"]
```


**Option 2**
```
"author": "Author 1, Author 2"
```

**Comment by lobsam** [comment]
@tenzin3 pecha.org api accept only one author as of now>
if there is more than one authors for a book then i think we can pass author as a string with coma (,) seperated.
like you mentioned `"author": "Author 1, Author 2"`

**Comment by tenzin3** [comment]
> @tenzin3 pecha.org api accept only one author as of now> if there is more than one authors for a book then i think we can pass author as a string with coma (,) seperated. like you mentioned `"author": "Author 1, Author 2"`

Thank you @lobsam , I would do that

**Comment by lobsam** [comment]
@tenzin3 can you make `author` as list instead of string 
for example `author : [author1, author2]`.
i just realized we need list of author in text index in pecha.org

**Comment by tenzin3** [comment]
@lobsam as per your instructions for changes, i have done it, below is the how it will serialized json would look like
```

{
  "target": {
    "books": [
      {
        "title": [
          " Source Title 1",
          " Source Title 1"
        ],
        "author": [
          " Source Author 1",
          " Source Author 1"
        ],
        "language": "bo",
        "version_source": "www.github.com/PechaData/IDBEEDAAE/base/389e.txt",
        "direction": "ltr",
        "content": [
          [
            "སངས་རྒྱས་དང་བྱང་ཆུབ་སེམས་དཔའ་ཐམས་ཅད་ལ་ཕྱག་འཚལ་ལོ།།<br> བདེ་གཤེགས་ཆོས་ཀྱི་སྐུ་མངའ་སྲས་བཅས་དང་།།<br> ཕྱག་འོས་ཀུན་ལའང་གུས་པར་ཕྱག་འཚལ་ཏེ།།<br><br>",
            "བདེ་གཤེགས་སྲས་ཀྱི་སྡོམ་ལ་འཇུག་པ་ནི།།<br> ལུང་བཞིན་མདོར་བསྡུས་ནས་ནི་བརྗོད་པར་བྱ།།<br><br>",
            "སྔོན་ཆད་མ་བྱུང་བ་ཡང་འདིར་བརྗོད་མེད།།<br> སྡེབ་སྦྱོར་མཁས་པའང་བདག་ལ་ཡོད་མིན་ཏེ།།<br> དེ་ཕྱིར་གཞན་དོན་བསམ་པའང་བདག་ལ་མེད།།<br> རང་གི་ཡིད་ལ་བསྒོམ་ཕྱིར་ངས་འདི་བརྩམས།།<br><br>",
            "དགེ་བ་བསྒོམ་ཕྱིར་བདག་གི་དད་པའི་ཤུགས།།<br> འདི་དག་གིས་ཀྱང་རེ་ཞིག་འཕེལ་འགྱུར་ལ།།<br><br>",
            "བདག་དང་སྐལ་བ་མཉམ་པ་གཞན་གྱིས་ཀྱང་།།<br> ཅི་སྟེ་འདི་དག་མཐོང་ན་དོན་ཡོད་འགྱུར།།<br>"
          ]
        ]
      }
    ]
  },
  "source": {
    "books": [
      {
        "title": [
          " Target Title 1",
          " Target Title 1"
        ],
        "author": [
          " Target Author 1",
          " Target Author 1"
        ],
        "language": "en",
        "version_source": "www.github.com/PechaData/IA4C08511/base/0d78.txt",
        "direction": "ltr",
        "content": [
          [
            "A Guide To The Bodhisattava's Way of Life Homage to all Buddha's and Bodhisattvas Respectfully I prostrate myself to the Sugatas Who are endowed with the Dharmakaya, As well as to their Noble Children And to all who are worthy of veneration.<br>",
            "Here I shall explain how to engage in the vows of the Buddha's Children, The meaning of which I have condensed in accordance with the scriptures.<br>",
            "Thete is nothing hete that has not been explained before And I have no skill in the art of thetotic; Therefore, lacking any intention to benefit others, I write this in order to acquaint it to my mind.<br>",
            "For due to acquaintance with what is wholesome, The force of my faith may for a short while increase because of these.<br>",
            "If, however, these are seen by others Equal in fortune to myself, it may be meaningful."
          ]
        ]
      }
    ]
  }
}
```

**Comment by lobsam** [comment]
@tenzin3 we need book title as sting not list 

```
"title": "title of book"
```
