### ISSUE TITLE
OPT20003: Chonjuk Aligment Parser (new format)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#24]
## Description
We have recieved new format for alignment input. So we need an parser to carter to this kind of input as well.

## Expected Output
Proper OPA and OPF format.

## New Alignment input format

- the root-commentary alignment mapping is annotated in the following format  13. in both root-text file and the commentary file
- segments in the commentary files are meaning segments NOT root-commentary alignment segments
- meaning segments start with a) file start or b) 2 line returns and end with a) text end or b) 2 line returns
- meaning segments in a commentary which are linked to a root text segment start with a  root-commentary alignment tag (i.e. 13.) and finish at the end of that meaning segment
- meaning segments in a commentary may or may not be linked to a root text segment
- 1 root text segment can be linked to one or many commentary segments
- 1:many mappings are annotated in two formats: a) 1,2,3 or b) 1-3 or c) 1-3,10
- root-commentary mapping in 1:many instances has to be done individually for each meaning segment. i.e. given the tag  1-3,10 in a commentary,  that segment should be linked to each of the root-text segments 1, 2, 3 and 10

## Alignment mapping format

![Image](https://github.com/user-attachments/assets/145b6eeb-bba6-44da-9534-3957e1872a7c)

## Implementation Steps

- [x] make test case
- [x] parse content into segments
- [x] identify meaning segments and root segments
- [x] identify sapche annotations
- [x] identify meaning segments and comment segments
- [x] write meaning segments to stam
- [x] write root segments to stam
- [x] write comment segments to stam
- [x] write sapche annotations
- [x] write metadata
- [x] map root and commentary alignment
- [x] write to alignment

**Comment by tenzin3** [comment]
### **Code snippet to retrieve required annotations from the annotations.**

Note: In current annotation store

- meaning segment annotations has text selector pointing to base file
- root segment annotations has annotation selector pointing to the meaning segment annotation.

```
from stam import AnnotationStore

from openpecha.pecha.layer import LayerCollectionEnum, LayerGroupEnum, LayerEnum


pecha = AnnotationStore(file="file_path.json")

ann_dataset = LayerCollectionEnum.root_commentory.value 
ann_key = LayerGroupEnum.structure_type.value 
ann_value = LayerEnum.meaning_segment.value

for meaning_segment_ann in pecha.data(set=ann_dataset, key=ann_key, value=ann_value).annotations():
    root_segment_ann = next(meaning_segment_ann.annotations())
    
```

**Comment by tenzin3** [comment]
## Root Text
```
1. v1大方廣佛華嚴經·v2入不思議解脫境界普賢行願品

2. 梵文名為：阿雅 拔雜 札雅 巴倪 達拿 喇雜

3. 藏文名為：帕巴 嗓缽 倔巴 夢浪 給 嘉缽

4. 禮敬聖文殊童子

5. 所有十方世界中，三世一切人師子，我以清淨身語意，一切遍禮盡無餘。

6. 普賢行願威神力，普現一切如來前，一身復現刹塵身，一一遍禮刹塵佛。

7. 於一塵中塵數佛，各處菩薩眾會中，無盡法界塵亦然，深信諸佛皆充滿。

8. 各以一切音聲海，普出無盡妙言辭，盡於未來一切劫，讚佛甚深功德海。

9. 以諸最勝妙華鬘，伎樂塗香及傘蓋，如是最勝莊嚴具，我以供養諸如來。

10. 最勝衣服最勝香，末香燒香與燈燭，一一皆如妙高聚，我悉供養諸如來。
```

## Root Text serialized json
```
{
  "books": [
    {
      "title": "title",
      "language": "bo",
      "author": "author name",
      "versionSource": " ",
      "content": [
        "v1大方廣佛華嚴經·v2入不思議解脫境界普賢行願品",
        "梵文名為：阿雅 拔雜 札雅 巴倪 達拿 喇雜",
        "藏文名為：帕巴 嗓缽 倔巴 夢浪 給 嘉缽",
        "禮敬聖文殊童子",
        "所有十方世界中，三世一切人師子，我以清淨身語意，一切遍禮盡無餘。",
        "普賢行願威神力，普現一切如來前，一身復現刹塵身，一一遍禮刹塵佛。",
        "於一塵中塵數佛，各處菩薩眾會中，無盡法界塵亦然，深信諸佛皆充滿。",
        "各以一切音聲海，普出無盡妙言辭，盡於未來一切劫，讚佛甚深功德海。",
        "以諸最勝妙華鬘，伎樂塗香及傘蓋，如是最勝莊嚴具，我以供養諸如來。",
        "最勝衣服最勝香，末香燒香與燈燭，一一皆如妙高聚，我悉供養諸如來。"
      ],
      "direction": "ltr"
    }
  ]
}
```


## Commentary Text
```
<sapche>乙二 正頌
丙一 頌正示行願
丁一 正頌行願
戊一 頌第一願</sapche>

4. 行願之名雖有十義，意祇有七，以後三合故。初二句頌所禮，次一句頌能禮，第四句明周遍，第五句辯遍因。謂所以能如是周遍者，全仗普賢行願威神之力故也。後三句別顯禮相。謂一一佛所，各有多身；一一己身，能起多禮。

1-3. 經云：一一如來所，一切剎塵禮。即此意也。

<sapche>乙二 正頌
丙一 頌正示行願
丁一 正頌行願
戊一 頌第一願</sapche>

1-3,5. 行願之名雖有十義，意祇有七，以後三合故。初二句頌所禮，次一句頌能禮，第四句明周遍，第五句辯遍因。謂所以能如是周遍者，全仗普賢行願威神之力故也。後三句別顯禮相。謂一一佛所，各有多身；一一己身，能起多禮。

6. 經云：一一如來所，一切剎塵禮。即此意也。

```

## Commentary Text serialized json
```
{
  "books": [
    {
      "title": "title",
      "language": "bo",
      "author": "author name",
      "versionSource": " ",
      "content": [
        "<sapche>乙二 正頌\n丙一 頌正示行願\n丁一 正頌行願\n戊一 頌第一願</sapche>",
        "<1><1>經云：一一如來所，一切剎塵禮。即此意也。",
        "<1><1>行願之名雖有十義，意祇有七，以後三合故。初二句頌所禮，次一句頌能禮，第四句明周遍，第五句辯遍因。謂所以能如是周遍者，全仗普賢行願威神之力故也。後三句別顯禮相。謂一一佛所，各有多身；一一己身，能起多禮。",
        "<sapche>乙二 正頌\n丙一 頌正示行願\n丁一 正頌行願\n戊一 頌第一願</sapche>",
        "<1><2>經云：一一如來所，一切剎塵禮。即此意也。",
        "<1><2>行願之名雖有十義，意祇有七，以後三合故。初二句頌所禮，次一句頌能禮，第四句明周遍，第五句辯遍因。謂所以能如是周遍者，全仗普賢行願威神之力故也。後三句別顯禮相。謂一一佛所，各有多身；一一己身，能起多禮。",
        "<1><3>經云：一一如來所，一切剎塵禮。即此意也。",
        "<1><3>行願之名雖有十義，意祇有七，以後三合故。初二句頌所禮，次一句頌能禮，第四句明周遍，第五句辯遍因。謂所以能如是周遍者，全仗普賢行願威神之力故也。後三句別顯禮相。謂一一佛所，各有多身；一一己身，能起多禮。",
        "<1><4>行願之名雖有十義，意祇有七，以後三合故。初二句頌所禮，次一句頌能禮，第四句明周遍，第五句辯遍因。謂所以能如是周遍者，全仗普賢行願威神之力故也。後三句別顯禮相。謂一一佛所，各有多身；一一己身，能起多禮。",
        "<1><5>行願之名雖有十義，意祇有七，以後三合故。初二句頌所禮，次一句頌能禮，第四句明周遍，第五句辯遍因。謂所以能如是周遍者，全仗普賢行願威神之力故也。後三句別顯禮相。謂一一佛所，各有多身；一一己身，能起多禮。",
        "<1><6>經云：一一如來所，一切剎塵禮。即此意也。"
      ],
      "direction": "ltr"
    }
  ]
}
```

**Comment by lobsam** [comment]
@tenzin3 we need to add ` "base_text_titles": "root text title"` in commentary text .

**Comment by tenzin3** [comment]
@lobsam , One question i have , what is ``` "base_text_titles": "root text title"```.
Should this be same as title of the root text ?

**Comment by lobsam** [comment]
> @lobsam , One question i have , what is ` "base_text_titles": "root text title"`. Should this be same as title of the root text ?

Yes, base_text_title is root title

**Comment by tenzin3** [comment]
> > [@lobsam](https://github.com/lobsam) , One question i have , what is ` "base_text_titles": "root text title"`. Should this be same as title of the root text ?
> 
> [@tenzin3](https://github.com/tenzin3) Yes, base_text_title is root title

Oo thank you for the quick reply and clarification.
