### ISSUE TITLE
OPT20014: Create Structure Annotations for Chonjuk Data

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#30]
## Description 
We are planning to implement [DTS Specifications](https://distributed-text-services.github.io/specifications/) to develop a text api. One of the key endpoints is the [Navigation endpoint](https://distributed-text-services.github.io/specifications/versions/unstable/#navigation-endpoint), which helps retrieve specific text by allowing users to navigate through the content. To ensure proper functionality and testing of this feature, we are preparing structured annotations for the [Chonjuk dataset](https://github.com/Esukhia/chojuk-alignement).

## Requirement

- The data should be Chonjuk data.
- Each structural annotation must include necessary metadata, such as ID, title, etc.
- Higher-level structural annotations should have the capability to reference or call lower-level structural annotations.

## Chonjuk Data and Annotation Illustration
![Image](https://github.com/user-attachments/assets/97f5b0cc-f915-45f8-bdb5-2fc98c21cfcb)

## Expected Output
An OPF/Pecha for Chonjuk with three levels of structural annotations.

## Implementation Steps
- [x] text segmenter
- [x] annotate in stam
- [x] save annotation
- [ ] metadata annotation

annotation on annotation
- [x] load higher level annotation
- [ ] annotate on higher level annotation

**Comment by tenzin3** [comment]
chonjuk data [chosen](https://github.com/Esukhia/chojuk-alignement/blob/master/D3872-final/%E0%BD%90%E0%BD%B4%E0%BD%93%E0%BC%8B%E0%BD%98%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%82%E0%BD%B2%E0%BC%8B%E0%BD%A2%E0%BE%A9%E0%BC%8B%E0%BD%96%E0%BC%8D.txt)

**Comment by tenzin3** [comment]
**The Pecha Parser is designed with the following key principles in mind:**

- High Abstraction: The parser provides a high level of abstraction to simplify its use.
- Custom Pipeline Flexibility: Users can create custom pipelines to suit their specific needs.


**The parser operates with the following logic:**

1. Input Text: Accepts the text to be processed.
2. Segmenter: Segments the text using one of the following methods:
    Space Segmenter
    New Line Segmenter
    Regex Segmenter
3. Annotation Name: Assigns a name to the segmented text. The annotation name must be selected from a predefined list of enums.

**Comment by tenzin3** [comment]
## Read annotations and its annotation data in stam
```py
from stam import AnnotationStore


stam_obj = AnnotationStore(file="annotation_store_path_str.json")

anns = list(stam_obj.annotations())

ann_data = []
for ann in anns:
    curr_data = {}
    curr_data["content"] = str(ann)
    for data in ann:
        curr_data[data.key().id()] = str(data.value())
    ann_data.append(curr_data)

print(ann_data)

```

**Comment by tenzin3** [comment]
## Issues with new AnnotationSubStore 

**1.location of annotation data:** when creating annotations in AnnotationStore based on the annotations containing in the AnnotationSubStore using annotation selector, it is storing annotation data it the AnnotationSubStore rather than storing in the AnnotationStore.

**2.AnnotationStore annotations function:** When calling annotations function from the AnnotationStore, it is working properly but it is retrieving the annotations from the AnnotationSubStore as well. 

**3.@include path:** For our project, having our defined data folder structure, we are in nature forced store the base file and annotation store files in separate folder and so rather than saving the annotation_store directly using `set_filename` and `save` function. We are converting annotation to json string using `to_json_string` and then modified the path in relative format such as `../../base/7906.txt`. This is allowing us to have files in different folder and is ease of use. But in AnnotationSubStore, when we are using `to_json_string` from AnnotationStore, the dependency AnnotationSubStore which we have modified the paths in `@include` as relative are automatically being converted to absolute path.

**Comment by tenzin3** [comment]
I have created an issue regarding  STAM  [here.](https://github.com/annotation/stam/issues/31)

**Comment by tenzin3** [comment]
## Framework Design

**1.Text Processing:**
- Split the text into atomic units
- An atomic unit is defined as a string split by a new line.

**2.Condition Check:**
- Verify if the atomic units contain specific annotations.
- A particular regex sometimes cant extract all annotations.

**3: Modular Design:** 
- Each function should perform only one task to ensure high reusability.

**4:Custom Pipeline:** 
- Users should be able to create their own custom processing pipelines.

![Image](https://github.com/user-attachments/assets/202cda7e-1bf8-4e93-ae12-8cbb9de016d1)

**Comment by tenzin3** [comment]
```
For Metadata:
ann_store: id = Pecha ID
ann_data_set: id = Meta_Data


For Translation and version:
ann_store: id = Pecha ID
ann_data_set: id = Translation 

ann_data:
    key: Translation_Segment
    value: Tibetan_Segment

    key: Translation_Segment
    value: Englist_Segment



For Root and Commentary:
ann_store: id = Pecha ID
ann_data_set: id = Root_Commentary

ann_data:
    key: Associated_Alignment    
    value: Root_Segment

    key: Associated_Alignment
    value: Commentary_Segment


For OPF:
ann_store: id = Pecha ID
ann_data_set: id = Structure_Annotation

ann_data:
    key: Structure_Type
    value: Chapter

    key: Structure Type
    value: Tsawa

    key: Structure Type
    value: Meaning_Segment

```
