### ISSUE TITLE
OPT20015: Build navigation endpoint for Chonjuk Data

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#31]
## Description 
We are planning to implement [DTS Specifications](https://distributed-text-services.github.io/specifications/) to develop a text api. One of the key endpoints is the [Navigation endpoint](https://distributed-text-services.github.io/specifications/versions/unstable/#navigation-endpoint), which helps retrieve specific text by allowing users to navigate through the content.

## Data
The data to be used for used for this navigation endpoint will be output from this [issue](https://github.com/OpenPecha/toolkit-v2/issues/30#issue-2507424712).

## Expected Output
The Navigation endpoint should return a hierarchical structure of the text in JSON-LD format, with each node containing identifiers, labels, position, and links to parent/child nodes. It may include optional metadata.

## Implementation Steps

- [ ]  Load the desired pecha/opf.
- [ ]  Retrieve annotations from the annotation store.
- [ ]  Retrieve annotation metadata from the annotation store.
- [ ]  Output node information as JSON.
- [ ]  Output parent/child node information as JSON.
