### ISSUE TITLE
OPT2018: Update alignment json serializer

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#36]
## Description 
There is an existing JSON serializer for the pecha.org website, but a few updates are needed

- **Include book category information** in the JSON file.
- **Combine versions and translations** into a single JSON file.
- **Add source and target aspects** to the commentary when converting it to a JSON format.

## Important Notes:

- For book titles, include the language name at the end, such as "Book Title[fr]" for French, except for Tibetan and English.
- Include the book's metadata in the last category along with the book details. This category will be used for mapping with commentaries.
- In versions and translations, the Tibetan root text and version should be placed in the target, while all other translations and versions should be in the source.
- Each commentary should be in a separate JSON file. The content should be in the target, while the source should contain details of the root text, but the content should remain empty.

## Expected Output
[Input](https://drive.google.com/drive/folders/1_Hp9hTi0qIb19CRrRSobdm9HpFVOv9pr)
[Root json output](https://github.com/OpenPecha/pecha.org-api/blob/main/jsondata/texts/baseText/003-b0.json)
[Commentary json output](https://github.com/OpenPecha/pecha.org-api/blob/main/jsondata/texts/commentaryText/004.ch-1.json)

## Implementation Steps
- [ ] script to get book's category
- [x] build alignment framework
- [x] develop translation serializer
- [x] develop commentary serializer

**Comment by lobsam** [comment]
@tenzin3 all above details looks good for me except `Combine versions and translations into a single JSON file.`

As we discuss before we need to keep version and translation text in seperate json file.

**Comment by tenzin3** [comment]
This card tasks has been completed in different cards.

Script to get the book category would be made in a new card.
