### ISSUE TITLE
OPT2023: Text File Parser into OPF

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#43]
## Description
Text File Parser into OPF with proper abstraction.

## Requirements

1. Parser abstraction class
2. opf writer with proper specification requirement
3. text file parser meeting requirement 2
4. clean base file with raw string
5. separate parser and opf writer module

## Data
Chonjuk chapter

## Expected Output
An OPF.

## Implementation Steps

- [x] parser abstraction class
- [x] chapter span extraction with clean base
- [x] modify Pecha abstraction a higher level
