### ISSUE TITLE
Chonjuk Alignment parser (4 days)

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#6]
## Description
The task involves parsing Chonjuk sources (including both root text and commentary) and generating an alignment object that can be saved in the STAM data format. STAM is a low-level annotation model coded in Rust. Our goal is to directly implement our data source into STAM without any intermediate layers or abstractions that could slow down data exchange.

## Requirement
- Proper data validation.(This refers to annotation category and annotation type).
- Each annotation file(root text and commentary) should be stored as different individual AnnotationStore.
- AnnotationDataset name of all (translation segments and translation alignment file) should have same id.

## Expected Output
The expected output is the parsed Chonjuk source (root text and commentary) mapped accurately into the STAM format.

## Implementation Plan

![Image](https://github.com/OpenPecha/toolkit-v2/assets/52460417/9324b53c-330a-478c-8f31-094087ca9895)

## Implementation Steps

- [x] parse and write translation segment to stam
- [x] read segment with pecha class
- [x] write alignment to stam
- [x] read alignment from stam
- [x] write metadata file to stam
- [x] read metadata file from stam
- [x] modifications (listed  [here](https://github.com/OpenPecha/toolkit-v2/issues/6#issuecomment-2252053843) )

**Comment by kaldan007** [comment]
done with parser. will discuss the need of wrapper class or not

**Comment by ta4tsering** [comment]
working on the metadataselector in stam

**Comment by tenzin3** [comment]
Had demo meeting with NT, kaldan and tashi tsering on 25th July 24. 
Following changes need to be implemented to package

- include layer in alignment mapping 
- basefile naming be set to 4 digits
- change name comment -> commentary
- make metadata as a different ann store 
- exclude meta data ann from alignment anns 

included an additional item as modification

**Comment by tenzin3** [comment]
@ngawangtrinley , @kaldan007 , @ta4tsering , @10zinten . If there are any suggestions, please comment below

from [chojuk alignment]( https://github.com/Esukhia/chojuk-alignement)
following has been parsed and uploaded to [PechaData](https://github.com/PechaData/)

Following are the folder name and its corresponding Alignment ID:

- D3872-final  : AFA7368EE
- D3874-final  : A4E5EBEAE
- D3875-final  : A2A8D60A0
- D3876-final  : A28F2E712
- D3877-final  : AA3373D83
- D3878-final  : A0374036F
- D3879-final  AF7E290F1
- D3880-final  : A3AB0E101
- Kunpal-final: AC669A10E
- Thubcho-final: ADB1AE4AB
- Thokme-final: A275C7080

### Important Notes

- From the following , comparing Tsawa/Root files (base file) only Kunpal, Thubcho and Thokme were identical.(Same Tsawa Pecha) Else all tsawa  were different. 
- The folder name(such that D3872-final, ....)  are presented in the metadata.json.
- MetaData for Pechas been inserted with dummy values due to lack of metadata.
- Files with encoding UTF-16 E has been converted to UTF-8 file.
- Newlines in files has been normalized.(See below pictures)


#### Before
![Image](https://github.com/user-attachments/assets/fb0b7521-ceb6-441a-a7c5-1e723ecbd512)
#### After
![Image](https://github.com/user-attachments/assets/2d33c08c-7f8c-4506-8308-096c0624b3de)

**Comment by ngawangtrinley** [comment]
Can you add some translations? By the way, did @10zinten get started on the base update? You will need to transfer the translation segments to the root text

**Comment by tenzin3** [comment]
@ngawangtrinley yes I talked with @10zinten and he has already started working on base update mechanism feature. The link you provided has 3 translation tibetan and english pairs. I would do that.

**Comment by ngawangtrinley** [comment]
You can keep it in a different base version and we will then transfer the bo-en mapping on the clean base

**Comment by tenzin3** [comment]
@ngawangtrinley 

Translation from [nalanda-mt](https://github.com/OpenPecha/nalanda-mt ) has been converted and below are their following alignment id.

TM0876: AA0868822
TM2380: A7CF01CC0
TM3841: A49E97481

**Important Note:**
Translation mapping has been done on clean file. and file with emojis (or qc) has been saved with suffix **basefile_name-qc.txt**

![Image](https://github.com/user-attachments/assets/6a311e35-9bc1-41bc-ab8a-baa47ab06a6d)
