### ISSUE TITLE
OPT20027: Google Docs Parser

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#63]
## Description
Parser for root and commentary text into OPF format.

## Important Note
Store annotation of meaning segment and its (root/commentary) mapping only.
Commentary pecha should store the detail of root pecha such as Pecha id , ....

## Input 
Google docx file

## Expected Output
Parser able to give an OPF STAM format.

## Implementation Steps
- [x] root pecha parser
- [x] commentary pecha parser
- [x] serializer
- [ ] modification in serializer

**Comment by tenzin3** [comment]
Important Notes when coding the serializer:

- more than one commentary for each root file.
- sapche annotation should be there.
- JSON output format should be refer from this [documentation](https://github.com/OpenPecha/pecha.org-data/blob/main/docs/sample_files/example_4_simple-text_commentary.json).

**Comment by tenzin3** [comment]
a serialized json for dolma 21 root and commentary uloaded to [here](https://staging.pecha.org/Test_Commentary.1.4?vhe=%E0%BD%A6%E0%BE%92%E0%BE%B2%E0%BD%BC%E0%BD%A3%E0%BC%8B%E0%BD%98%E0%BC%8B%E0%BD%89%E0%BD%BA%E0%BD%A2%E0%BC%8B%E0%BD%82%E0%BD%85%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BE%9F%E0%BD%BC%E0%BD%91%E0%BC%8B%E0%BD%94%E0%BC%8D&lang=bi)
[root_commentary.json](https://github.com/user-attachments/files/17743197/root_commentary.json)

**Comment by tenzin3** [comment]
base_text_titles should be in "english."
root and commentary file should be separate.
tibetan should be in target.(both root and commentary)
