### ISSUE TITLE
OPT20028:New alignment serializer

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#69]
## Description
New alignment serializer.

## Expected Output
JSON file able to work in pecha.org.

## Input
Two pecha in opf format.

## Implementation Steps
- [x] understand the expected json output
- [x] read pecha opf
- [x] prepare base json format
- [x] main serializer script
- [x] test in pecha.org staging

**Comment by tenzin3** [comment]
With discussion after @lobsam, this is the [expected JSON output file](https://github.com/OpenPecha/pecha.org-data/blob/main/docs/sample_files/example_2_simple-text_with_translation.json) for this issue.

**Comment by tenzin3** [comment]
Made BaseAlignmentSerializer class to normalize the future Alignment serializer.

**Comment by tenzin3** [comment]
Tested the serialized output with @lobsam  and @Lungsangg.  Made neccessary changes and uploaded to [here](https://staging.pecha.org/Test_Translation?tab=contents).
