### ISSUE TITLE
OPT20032: Update Google docs Commentery Parser or Formatter

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#75]
## Description
The Google Doc parser needs to support parsing Sapche annotations in addition to its current functionality. The Sapche annotations should be extracted and stored in a separate STAM layer.

## Expected Output
The parser should successfully extract Sapche annotations from Google Docs and store them in a dedicated STAM layer.

## Implementation Steps

- [x] Prepare Test data
- [x] Extract Sapche Annotation Text
- [x] Write Sapche Annotations

### Card Reviewer:

- [x] @ta4tsering

**Comment by tenzin3** [comment]
The above issue of not able to extract the Numbered list is not valid as this was issue from the Data Team.
Had meeting with Yeshi Lhundop and discussed about the neccessary changes needed.
