### ISSUE TITLE
OPT20033: Commentery Serializer from OPF to PechaDB

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#77]
## Description 
Develop a commentary serializer to convert OPF data into PechaDB format.

## Expected Output
Develop a commentary serializer to convert OPF data into PechaDB format.

## Implementation Steps
- [x] Understand the JSON Format
- [x] Define the Base JSON Format in serializer
- [x] Read OPF and Populate JSON
- [x] Update the Category Spreadsheet
- [x] Integrate Serializer with Categorizer Package
- [ ] Test with pecha.org

## Card Reviewer
- [x] @lobsam

**Comment by tenzin3** [comment]
Met with @lobsam and discuss the required JSON format. [here](https://github.com/OpenPecha/pecha.org-api/blob/main/jsondata/texts/commentaryText/%E0%BD%80%E0%BD%B4%E0%BD%93%E0%BC%8B%E0%BD%96%E0%BD%9F%E0%BD%84%E0%BC%8B%E0%BD%A6%E0%BE%A8%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%A3%E0%BD%98%E0%BC%8B%E0%BD%82%E0%BE%B1%E0%BD%B2%E0%BC%8B%E0%BD%A0%E0%BD%91%E0%BE%B2%E0%BD%BA%E0%BD%93%E0%BC%8B%E0%BD%96%E0%BE%B1%E0%BD%BA%E0%BD%91%E0%BC%8B%E0%BD%8A%E0%BE%B0%E0%BD%B2%E0%BC%8B%E0%BD%80%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%90%E0%BD%B4%E0%BD%A2%E0%BC%8B%E0%BD%98%E0%BD%A6%E0%BC%8B%E0%BD%96%E0%BD%A6%E0%BD%A3%E0%BC%8B%E0%BD%96%E0%BC%8D.json)

**Comment by tenzin3** [comment]
Requirements:

## 1.Multilingual Support:
The system should support multiple languages, including Traditional Chinese, French, Tibetan, English, and more.

## 2.File Pointer by ID:
The pointer to each file should be its unique file ID.This ID should be use to get the category from the pecha org tools.

## 3.Multiple Placement in a Tree-Like Structure:
A single file can exist in multiple locations within a hierarchical structure. For example:

Dalai Lama -> Books -> Art of Happiness
Spiritual Books -> Art of Happiness

## 4.Handling Language Variations in Titles:
In the current framework (Sefaria), every Pecha is required to have titles in both Tibetan and English.
In the new architecture being developed by Samten, there might be cases where certain Pechas lack titles in some languages. The system must account for such scenarios and handle them appropriately.

**Comment by tenzin3** [comment]
@lobsam , we finished with serialization for commentary first.Can you look and see the neccessary changes.We would test when we are ready the root serialization.

We only had data for tibetan text(in the target). And since we dont have other language, I have given category , title all in english but left the content empty as dictionary.Please have a look and share your thoughts.

```python
{
  "source": {
    "categories": [
      {
        "name": "The Buddha's Teachings",
        "enDesc": "",
        "enShortDesc": ""
      },
      {
        "name": "Vajra Cutter",
        "enDesc": "",
        "enShortDesc": ""
      },
      {
        "name": "Commentaries",
        "enDesc": "",
        "enShortDesc": ""
      },
      {
        "name": "Vajra Cutter",
        "enDesc": "",
        "enShortDesc": ""
      }
    ],
    "book": [
      {
        "title": "Vajra Cutter",
        "language": "en",
        "versionSource": "https://library.bdrc.io/show/bdr:WA1KG12670?tabs=bdr:MW3JT13747,bdr:W3JT13747",
        "direction": "ltr",
        "completestatus": "done",
        "content": {}
      }
    ]
  },
  "target": {
    "categories": [
      {
        "name": "སངས་རྒྱས་ཀྱི་བཀའ།",
        "heDesc": "",
        "heShortDesc": ""
      },
      {
        "name": "རྡོ་རྗེ་གཅོད་པ།",
        "heDesc": "",
        "heShortDesc": ""
      },
      {
        "name": "འགྲེལ་པ།",
        "heDesc": "",
        "heShortDesc": ""
      },
      {
        "name": "རྡོ་རྗེ་གཅོད་པ།",
        "heDesc": "",
        "heShortDesc": ""
      }
    ],
    "book": [
      {
        "title": "རྡོ་རྗེ་གཅོད་པ།",
        "language": "bo",
        "versionSource": "https://library.bdrc.io/show/bdr:WA1KG12670?tabs=bdr:MW3JT13747,bdr:W3JT13747",
        "direction": "ltr",
        "completestatus": "done",
        "content": {
          "མདོའི་ལུས་ཀྱི་འགྲེལ་པ།": {
            "data": [],
            "སངས་རྒྱས་ཀྱི་གདུང་རྒྱུན་མི་འཆད་པ་བསྟན་པ།": {
              "data": [
                "<1><1>རྒྱ་གར་སྐད་དུ། །ཨཱརྱ་བྷ་ག་བ་ཏཱི་པྲཛྙཱ་པཱ་ར་མི་ཏཱ་བཛྲ་ཙྪེ་དི་ཀཱ་ཡཱཿསཔྟ་དཱརྠ་ཊཱི་ཀཱ།"
              ]
            }
          },
          "ཚིག་གི་དོན་བཤད་པ།": {
            "data": [],
            "སངས་རྒྱས་ཀྱི་གདུང་རྒྱུན་མི་འཆད་པ་བསྟན་པ།": {
              "data": [
                "ཚིག་གི་དོན་བཤད་པ།\nསངས་རྒྱས་ཀྱི་གདུང་རྒྱུན་མི་འཆད་པ་བསྟན་པ།",
                "མཚུངས་མེད་སངས་རྒྱས་ཆོས་རྣམས་སྐྱེད་མཛད་ལ། །\nགང་ཞིག་ཆོས་དབྱིངས་གསོ་བའི་མ་མ་སྟེ། །\nདབྱེ་དཀའི་རྡོ་རྗེ་གཞན་དོན་གྲུབ་གང་ཡིན། །\nགང་ཞིག་བཟུང་བས་འཕགས་ཀུན་སྐྱེད་པའམ་ཡིན། །"
              ]
            }
          }
        }
      }
    ]
  }
}
```
