### ISSUE TITLE
OPT20032: Translation native segmentation parser

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#89]
## Description
A parser for translation texts in Google Docs, designed to handle Tibetan, English, and Chinese content.

## Implementation 
![Image](https://github.com/user-attachments/assets/f93a931b-c9e4-4715-8de9-4fa18bc1229e)

## Dummy Data
available [here](https://docs.google.com/spreadsheets/d/1YAZ5UTryCg1F6wggo9MqKwTb-dEkAhTTuU5xVBDizaU/edit?gid=0#gid=0)

## Important Note
The Tibetan Google Doc serves as the primary source, with other translations being based on this file. Therefore, the Tibetan OPF should include data from the English OPF and Chinese OPF, such as the OPF pecha id, basename, and layer name.

## Expected Output
Generates OPFs  for each translation document in Google Docs.

## Implementation Steps
- [x] get google doc content and parse
- [x] write tibetan google doc to opf
- [x] write english/chinese google doc to opf
- [x] update source opf 

## Reviewer
- [x] @ta4tsering

**Comment by ta4tsering** [comment]
isn't there should be a mapping between those Tibetan, English and Chinese OPFs ? how are we gonna store that mapping ? later on when we need to get the same text in other languages then how are we gonna know which OPFs are ?

**Comment by tenzin3** [comment]
> isn't there should be a mapping between those Tibetan, English and Chinese OPFs ? how are we gonna store that mapping ? later on when we need to get the same text in other languages then how are we gonna know which OPFs are ?

I did mentioned  in Important Note, Now I have also included it in the diagram.

**Comment by tenzin3** [comment]
Modifications

- hardcode title_short to title
- include metadata for base
- include translation_alignments

**Comment by tenzin3** [comment]
![Image](https://github.com/user-attachments/assets/d884acae-c8dc-4eca-a346-37f34e0021e8)

Mapping is kept such as here.
