### ISSUE TITLE
OPT20035: Translation alignment Transfer mechanism

### ISSUE THREAD

**Issue by ta4tsering** [OpenPecha/toolkit-v2#91]
## Description:
So we will have a `Tibetan Root Text segmented for Pecha Display` which we will name `P1`, which we will upload on the pecha.org. And then we will have same text `Tibetan Root text native segmented` which we will name `P2`.  And finally we will have other language translation of the Root text either aligned to `P1` or `P2`. since those aligned to `P1` can be directly serialized we don't need to transfer anything. But for those that are aligned to `P2` say `English root text aligned to P2` we will call it `P3`.  We will need to transfer the segmentation from `P2` to `P1` base and then create new layer. Then we will compare the new layer and the layer of the `P1` to create a new layer for the `P3`.

## Implementation Diagram:
![Image](https://github.com/user-attachments/assets/efdd8dfa-ae63-488a-9fac-c695777de9f1)

## Completion Criteria:
when `P3` or `English root text aligned to P2` is correctly aligned with `P1` or `Tibetan Root Text segmented for pecha display`.

## Subtask:

- [x] Understanding the current merge opf method available
- [x] Transfer L3 segments from P2 to P1 as L2 segments
- [x] In P1, compare L2 segments to L1 segments to derive C1 mapping
- [x] Use C1 mapping to ceate L5 English display segmentation
- [x] update the OPF metadata
- [x] Write Test

## Card Reviewer:

- [x] @tenzin3
