### ISSUE TITLE
OPT20033: Commentary native segmentation opf to pecha db json serializer

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#94]
## Description
A serializer is required to convert commentary data from Pecha OPF format into JSON for pecha.org with  [api](https://github.com/OpenPecha/pecha.org-api) platform. While the script for the conversion has been implemented, modifications are needed to meet the required standard format and enable successful uploads to pecha.org using the provided API.

## Dummy Data
Sample data is available [here](https://docs.google.com/spreadsheets/d/1YAZ5UTryCg1F6wggo9MqKwTb-dEkAhTTuU5xVBDizaU/edit?gid=0#gid=0).

## Desired Output
The JSON file, provided by Sandup after thorough testing and approval of all required formats, is now available here.
[standard_commentary.json](https://github.com/user-attachments/files/18108951/standard_commentary.json)

## Expected Output
Serialized JSON files for each commentary, meeting the required format, and successfully uploaded to the staging environment of pecha.org.

## Implementation Steps
- [x] Manually prepare JSON files for commentary document files.
- [ ] Test the JSON files with the pecha.org API.
- [x] Modify the script to generate the desired JSON.
- [ ] Upload the finalized JSON files to staging.pecha.org.

## Reviewer

- [x] @ta4tsering

**Comment by tenzin3** [comment]
To upload the Commentary JSON files via pecha.org-api

1. run commentaryToJson.py script to generate links..
2. run pechaAPI.py script to upload text and its commenary links
