### ISSUE TITLE
OPT20034: Commentary alignment Transfer mechanism

### ISSUE THREAD

**Issue by tenzin3** [OpenPecha/toolkit-v2#99]
## Description
For any pecha text, a commentary is typically created based on that specific root pecha. Each commentary may vary in its choice of words and segmentation.

For our website, pecha.org, we aim to display a particular pecha text and align all related commentaries with it. This makes the development of a commentary alignment annotation transfer mechanism essential.

## Implementation Steps
![Image](https://github.com/user-attachments/assets/2f92752a-a13c-4109-8420-5fa1b01413bf)

## Important Note
Translation alignment annotation transfer is already done.So refer from [here](https://github.com/OpenPecha/toolkit-v2/issues/91#issue-2732555144).

## Expected Output
A proper L5 segment layer in P3 pecha is created.

## Work Items
- [x] Prepare test data
- [x] create L2 segment layer in P1 pecha
- [x] update the alignment transfer in P1 pecha metadata
- [x] create C1 alignment
- [x] create L5 segment layer in P3 pecha
- [x] update the alignment transfer in P3 pecha metadata

## Reviewer
- [x] @ta4tsering
